### ISSUE TITLE
wifi-password

### ISSUE THREAD

**Issue by yg** [denorg/denorg#3]
**What's the proposed name of the project?**

Get current wifi password

**Is this a port of a NPM package? If yes, link the package here.**

https://www.npmjs.com/package/wifi-password

**Example API**

```ts
wifiPassword('yg')
```

**Comment by AnandChowdhary** [comment]
Haha this is pretty cool, let's do it!

These are some good ones too: http://tidelift.com/subscription/pkg/supported-open-source-packages
